language: C
sudo: true
script:
  - cat /etc/lsb-release
  - sudo apt-get update
  - sudo apt-get --force-yes dist-upgrade
  - sudo reboot
  - cat /etc/lsb-release
  - ./tests/script/prepare_for_test
  - ./tests/script/exec_all_unit
