#!/bin/bash
set -xueo pipefail
export LANG=C LC_ALL=C

prepare() {
  sudo apt-get update
  sudo apt-get --quiet -y install \
    git pkg-config make autoconf libtool yasm liburcu-dev libzookeeper-mt-dev qemu check python zookeeper xfsprogs bc gcc g++
}

#main
prepare
